name: Feed Packages

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  build:
    name: ${{ matrix.arch }} ${{ matrix.branch }} build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - arm_cortex-a5_vfpv4
          - arm_cortex-a7_neon-vfpv4
          - arm_cortex-a8_vfpv3
          - arm_cortex-a9
          - arm_cortex-a9_vfpv3-d16
          - arm_cortex-a9_neon
          - arm_cortex-a15_neon-vfpv4
          - aarch64_cortex-a53
          - aarch64_cortex-a72
          - aarch64_generic
          - mips_24kc
          - mips_4kec
          - mips_mips32
          - mipsel_24kc
          - mipsel_24kc_24kf
          - mipsel_74kc
          - mips64_octeonplus
          - i386_pentium4
          - x86_64
        branch:
          - alpha
          - stable

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare for stable
        if:  matrix.branch == 'stable'
        run: |
          . mihomo/stable
          # add PKG_VERSION to first line
          sed -i "1s/^/PKG_VERSION:=$PKG_VERSION\n/" mihomo/Makefile
          sed -i "s/PKG_RELEASE:=.*/PKG_RELEASE:=$PKG_RELEASE/" mihomo/Makefile
          sed -i "s/PKG_SOURCE_DATE:=.*/PKG_SOURCE_DATE:=$PKG_SOURCE_DATE/" mihomo/Makefile
          sed -i "s/PKG_SOURCE_VERSION:=.*/PKG_SOURCE_VERSION:=$PKG_SOURCE_VERSION/" mihomo/Makefile
          sed -i "s/PKG_MIRROR_HASH:=.*/PKG_MIRROR_HASH:=$PKG_MIRROR_HASH/" mihomo/Makefile
          sed -i "s/PKG_BUILD_VERSION:=.*/PKG_BUILD_VERSION:=$PKG_BUILD_VERSION/" mihomo/Makefile

      - name: Build
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}
          FEEDNAME: mihomo
          PACKAGES: luci-app-mihomo
          INDEX: 1
          KEY_BUILD: ${{ secrets.KEY_BUILD }}
          NO_REFRESH_CHECK: true

      - name: Compress
        run: |
          tar -c -z -f mihomo_${{ matrix.arch }}_${{ matrix.branch }}.tar.gz bin/packages/${{ matrix.arch }}/mihomo

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: mihomo_${{ matrix.arch }}_${{ matrix.branch }}
          path: mihomo_${{ matrix.arch }}_${{ matrix.branch }}.tar.gz

  feed:
    needs: build
    name: feed
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch:
          - alpha
          - stable

    steps:
      - name: Download
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
      
      - name: Prepare
        run: |
          PUBLISH_BRANCH=gh-pages
          if [ "${{ matrix.branch }}" == "stable" ]; then
            PUBLISH_BRANCH=feed/stable
          fi
          echo "PUBLISH_BRANCH=${PUBLISH_BRANCH}" >> $GITHUB_ENV

      - name: Uncompress
        run: |
          ls mihomo_*.tar.gz | grep _${{ matrix.branch }}.tar.gz | xargs -n 1 tar -x -z -f

      - name: Feed
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: bin/packages
          force_orphan: true
          commit_message: Update Feed
          publish_branch: ${{ env.PUBLISH_BRANCH }}
